name: "Gitflow Versioning"
description: "Automates GitFlow: dev tags, release tags, patch increments, and branch management."
author: "bhcosta90"

inputs:
  mode:
    description: "Execution mode (dev, develop-patch, release-patch, finalize-package, finalize-release)"
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run GitFlow Logic
      shell: bash
      run: |
        set -e
        MODE="${{ inputs.mode }}"
        REF="${GITHUB_REF#refs/heads/}"

        # Auto-detect mode if not set
        if [[ -z "$MODE" ]]; then
          if [[ "$REF" == "main" ]]; then MODE="dev"; fi
          if [[ "$REF" == develop/* ]]; then MODE="develop-patch"; fi
          if [[ "$REF" == release/* ]]; then MODE="release-patch"; fi
        fi

        echo "Mode: $MODE, Branch: $REF"

        function create_dev_tag() {
          latest_stable=$(git tag --list --sort=-v:refname | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | head -n1)
          if [[ -z "$latest_stable" ]]; then
            major=0
            minor=0
            patch=0
          else
            IFS='.' read -r major minor patch <<<"$latest_stable"
            minor=$((minor+1))
            patch=0
          fi

          base_dev_prefix="dev-$major.$minor"
          latest_dev=$(git tag --list "${base_dev_prefix}.*" --sort=-v:refname | head -n1)
          if [[ -n "$latest_dev" ]]; then
            IFS='.' read -r _ _ dev_patch <<<"${latest_dev#dev-}"
            patch=$((dev_patch+1))
          fi
          echo "$base_dev_prefix.$patch"
        }

        function create_patch_tag() {
          latest_tag=$(git tag --sort=-v:refname | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | head -n1)
          IFS='.' read -r major minor patch <<<"$latest_tag"
          patch=$((patch+1))
          echo "$major.$minor.$patch"
        }

        function delete_dev_tags_branches() {
          # Deleta tags dev-* locais
          git tag -l "dev-*" | xargs -r git tag -d

          # Deleta tags dev-* remotas
          git ls-remote --tags origin "dev-*" | awk '{print $2}' | sed 's#refs/tags/##' | xargs -r -I {} git push origin :refs/tags/{} || true
        }

        case "$MODE" in
          dev)
            new_tag=$(create_dev_tag)
            git tag "$new_tag"
            git push origin "$new_tag" || true

            # Projeto zerado: se não houver tag stable, criar release/0x
            stable_tag=$(git tag --list --sort=-v:refname | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | head -n1)
            if [[ -z "$stable_tag" ]]; then
              release_branch="release/0x"
              git checkout -B "$release_branch"
              git push -u origin "$release_branch"
            fi
            ;;
          develop-patch|release-patch)
            new_tag=$(create_patch_tag)
            git tag "$new_tag"
            git push origin "$new_tag"
            ;;
          finalize-package)
            latest_stable=$(git tag --list --sort=-v:refname | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | head -n1)
            if [[ -z "$latest_stable" ]]; then
              new_tag="0.0.0"
              major=0
            else
              IFS='.' read -r major minor patch <<<"$latest_stable"
              minor=$((minor+1))
              patch=0
              new_tag="$major.$minor.$patch"
            fi

            # Cria a tag stable antes de deletar dev-*
            git tag "$new_tag" || true
            git push origin "$new_tag" || true

            # Cria develop/<major>x se não existir
            develop_branch="develop/${major}x"
            if ! git ls-remote --exit-code --heads origin "$develop_branch"; then
              git checkout -b "$develop_branch"
              git push -u origin "$develop_branch"
            fi

            # Agora deleta todas as tags dev-* locais e remotas
            delete_dev_tags_branches
            ;;
          finalize-release)
            latest_tag=$(git tag --sort=-v:refname | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | head -n1)
            IFS='.' read -r old_major old_minor old_patch <<<"$latest_tag"

            # Deleta develop da major atual
            old_develop_branch="develop/${old_major}x"
            if git ls-remote --exit-code --heads origin "$old_develop_branch"; then
                git push origin --delete "$old_develop_branch"
            fi

            # Próxima major
            new_major=$((old_major + 1))
            new_tag="$new_major.0.0"

            # Cria a tag stable antes de deletar dev-*
            git tag "$new_tag" || true
            git push origin "$new_tag" || true

            # Cria release/<old_major>x
            release_branch="release/${old_major}x"
            git checkout -B "$release_branch"
            git push -u origin "$release_branch"

            # Cria develop/<new_major>x
            develop_branch="develop/${new_major}x"
            git checkout -B "$develop_branch"
            git push -u origin "$develop_branch"

            # Remove tags dev-* locais e remotas
            delete_dev_tags_branches
            ;;
          *)
            echo "Invalid mode: $MODE"
            exit 1
            ;;
        esac
