name: Versioning - Auto

on:
  push:
    branches:
      - main
      - master
      - "[0-9]+.x"

permissions:
  contents: write

jobs:
  version-auto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Versioning Action (auto)
        uses: ./.
        with:
          mode: auto
