name: Versionamento

on:
  push:
    branches: [main, master, '*[0-9].x']
  workflow_dispatch:
    inputs:
      mode:
        description: 'Modo de execução'
        required: true
        default: 'release'

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bhcosta90/gitflow-versioning-action@main
        with:
          mode: ${{ github.event.inputs.mode || 'auto' }}