name: Git Flow Automation
on:
  push:
    branches: [main, master, 'develop/*', 'release/*']
  workflow_dispatch:
    inputs:
      mode:
        description: 'Choose Action mode'
        required: true
        type: choice
        options: [finalize-package, finalize-release]
        default: finalize-package

jobs:
  gitflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: {fetch-depth: 0}
      - name: Run Gitflow Versioning
        uses: bhcosta90/gitflow-versioning-action@main
        with:
          mode: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.mode || github.ref == 'refs/heads/main' && 'dev' || startsWith(github.ref, 'refs/heads/develop') && 'develop-patch' || startsWith(github.ref, 'refs/heads/release') && 'release-patch' }}
          changelog_entry: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.changelog_entry || '' }}
